### ISSUE TITLE
Add Python 3.8 minimal container

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#331]
# Background

- Python 3.6 is soon EOL

# Acceptance Criteria

- UDF run with Python 3.8 and all tests are green

**Comment by tkilias** [comment]
After some experimentation, we found that the compilation problem is caused by pymem.h which reference cpython/pymem.h in a subdirectory of the include directory. The following patch solve the issue in the bazel build.

```
diff --git a/exaudfclient/base/python_repository.bzl b/exaudfclient/base/python_repository.bzl
index 88b2695..7855277 100644
--- a/exaudfclient/base/python_repository.bzl
+++ b/exaudfclient/base/python_repository.bzl
@@ -19,7 +19,7 @@ def _get_includes_and_hdrs(config_binary,p_repository_ctx):
     includes = ",".join(['"%s"'%i for i in splitted_cleaned_includes] ) #example: ["\"/usr/include/python3.6m\"","\"/usr/include/python3.6m\""]
     print("python includes: %s"%includes)
 
-    hdrs = ",".join(['"%s/*.h"'%i for i in splitted_cleaned_includes] ) #example: ["\"/usr/include/python3.6m/*.h\"","\"/usr/include/python3.6m/*.h\""]
+    hdrs = ",".join(['"%s/**/*.h"'%i for i in splitted_cleaned_includes] ) #example: ["\"/usr/include/python3.6m/*.h\"","\"/usr/include/python3.6m/*.h\""]
     print("python hdrs: %s"%hdrs)
 
     return includes, hdrs
@@ -65,7 +65,7 @@ def _python_local_repository_impl(repository_ctx):
     build_file_content = """
 cc_library(
     name = "{name}",
-    srcs = glob(["{config_dir}/*.so"]),
+    srcs = glob(["{config_dir}/**/*.so"]),
     hdrs = glob([{hdrs}]),
     includes = [{includes}],
     defines = [{defines}],

```

Furthermore, we need a `install_python3.8_pip.sh` script to install it pip for python3.8. However, the python3.8-dev apt-package from ppa:deadsnakes doesn't include the distutils. We know that the package python3.8-full installed distutils, but we need to find which package includes it not install necessary stuff. 

We also encountered a few test failures:

```
command: bash -c "cd /tests/test/; python -tt "python3/all/getpass.py" --server '172.22.0.2:8888' --user 'sys' --password 'exasol' --script-languages 'PYTHON3=localzmq+protobuf:///bfsdefault/myudfs/python-3.7-minimal-EXASOL-6.2.0?lang=python#buckets/bfsdefault/myudfs/python-3.7-minimal-EXASOL-6.2.0/exaudf/exaudfclient_py3 PYTHON=builtin_python R=builtin_r JAVA=builtin_java' --loglevel=critical --driver=/downloads/ODBC/lib/linux/x86_64/libexaodbc-uo2214lv2.so  --jdbc-path /downloads/JDBC/exajdbc.jar  " 
environment: {'TRAVIS': '', 'TEST_ENVIRONMENT_TYPE': 'docker_db', 'TEST_ENVIRONMENT_NAME': 'python-3.7-minimal-EXASOL-6.2.0_build_run', 'TEST_DOCKER_NETWORK_NAME': 'db_network_python-3.7-minimal-EXASOL-6.2.0_build_run', 'TEST_DOCKER_DB_CONTAINER_NAME': 'db_container_python-3.7-minimal-EXASOL-6.2.0_build_run'}
E
======================================================================
ERROR: test_getuser (__main__.GetpassTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "python3/all/getpass.py", line 30, in test_getuser
    rows = self.query("select get_user_from_passwd()")
  File "/tests/lib/udf/__init__.py", line 213, in query
    return super(TestCase, self).query(*new_args, **kwargs)
  File "/tests/lib/exatest/testcase.py", line 191, in query
    return self._client.query(*args)
  File "/tests/lib/exatest/clients/odbc.py", line 43, in query
    q = self.cursor.execute(qtext, *args)
DataError: ('22002', u'[22002] [EXASOL][EXASolution driver]VM error: F-UDF-CL-LIB-1127: F-UDF-CL-SL-PYTHON-1002: F-UDF-CL-SL-PYTHON-1026: ExaUDFError: F-UDF-CL-SL-PYTHON-1114: Exception during run \nGET_USER_FROM_PASSWD:3 run\n  File "/usr/lib/python3.8/getpass.py", line 169, in getuser\n    return pwd.getpwuid(os.getuid())[0]\nKeyError: \'getpwuid(): uid not found: 500\'\n (Session: 1710804896614711296) (-1) (SQLExecDirectW)')

----------------------------------------------------------------------
Ran 1 test in 1.632s

FAILED (errors=1)
```

```
command: bash -c "cd /tests/test/; python -tt "generic/unicode.py" --server '172.22.0.2:8888' --user 'sys' --password 'exasol' --script-languages 'PYTHON3=localzmq+protobuf:///bfsdefault/myudfs/python-3.7-minimal-EXASOL-6.2.0?lang=python#buckets/bfsdefault/myudfs/python-3.7-minimal-EXASOL-6.2.0/exaudf/exaudfclient_py3 PYTHON=builtin_python R=builtin_r JAVA=builtin_java' --loglevel=critical --driver=/downloads/ODBC/lib/linux/x86_64/libexaodbc-uo2214lv2.so  --jdbc-path /downloads/JDBC/exajdbc.jar --lang python3 " 
environment: {'TRAVIS': '', 'TEST_ENVIRONMENT_TYPE': 'docker_db', 'TEST_ENVIRONMENT_NAME': 'python-3.7-minimal-EXASOL-6.2.0_build_run', 'TEST_DOCKER_NETWORK_NAME': 'db_network_python-3.7-minimal-EXASOL-6.2.0_build_run', 'TEST_DOCKER_DB_CONTAINER_NAME': 'db_container_python-3.7-minimal-EXASOL-6.2.0_build_run'}
.............E.....
======================================================================
ERROR: test_unicode_upper_is_subset_of_Unicode520_part1 (__main__.UnicodeData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tests/lib/udf/__init__.py", line 51, in wrapper
    return func(*args)
  File "generic/unicode.py", line 311, in test_unicode_upper_is_subset_of_Unicode520_part1
    ''')
  File "/tests/lib/udf/__init__.py", line 213, in query
    return super(TestCase, self).query(*new_args, **kwargs)
  File "/tests/lib/exatest/testcase.py", line 191, in query
    return self._client.query(*args)
  File "/tests/lib/exatest/clients/odbc.py", line 43, in query
    q = self.cursor.execute(qtext, *args)
ProgrammingError: ('42000', u'[42000] [EXASOL][EXASolution driver]object CODE not found [line 14, column 29] (Session: 1710805340052586496) (-1) (SQLExecDirectW)')

----------------------------------------------------------------------
Ran 19 tests in 17.341s
```

We also have a general problem with the ppa:deadsnakes they have a disclaimer that these python packages are not really production ready. They can't guarantee timely updates in case of vulnerabilities. I think, if we want to provide python3.8 we should use the version from ubuntu20.04 and build the flavor on this new base image.
